### ISSUE TITLE
go get fails

### ISSUE THREAD

**Issue by fkautz** [docker/golem#18]
Should go get work? If so, this is what I am seeing.
```
../../go/src/github.com/jlhawn/dockramp/build/util/util.go:78: undefined: v2.ValidateRepositoryName
```

If not, can we add a Makefile similar to docker?

**Comment by fkautz** [comment]
Also, README should be updated explaining how to get golem. :)

**Comment by dmcgowan** [comment]
Adding a Makefile is reasonable. It should build fine with godep.

Also note #1, building for mac is currently not supported since the binary builds itself into a docker image  with the current approach. I will likely just document this until figuring out what the best solution for developing Golem on the mac is, using a docker image will likely be the preferred usage.  Thanks for trying it out.

**Comment by fkautz** [comment]
I'm pulling from a linux system. :)

I'll submit a starter Makefile later on unless someone beats me to it.
